#!/usr/bin/env bash
# Build the Xash3D dedicated engine boot title for PS5 (Phase 5 gate 1).
#
# Produces dist/engine-boot/<title>/ with a signed eboot.bin that boots the
# Xash3D FWGS engine in dedicated mode, statically linked with the
# filesystem_stdio module and the hlsdk-portable server, and reports through
# ps5log/1. No shaders, no renderer: this gate proves filesystem, memory,
# threads, time, sockets and the three libc shims from a real title.
#
# Environment:
#   PS5_NATIVE_FOUNDATION  boilerplate checkout (default .deps/, pinned)
#   PS5LOG_DEV_CONF        private dev.conf copied into the title (optional)
#   XASH_GAME_DATA         private directory holding valve/ (optional; staged
#                          under dist/.../xash3d, never committed)
#   XASH_BOOT_MAP          map executed after boot (default c1a0)
#   XASH_GATE_SECONDS      queue "quit" after N seconds (default 90; 0 = never)
#   XASH_JOBS              parallel compile jobs (default nproc)
set -euo pipefail

root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
pin=37dd53602bdead63936f718004555ba10154be48
url=https://github.com/mpereiraesaa/ps5-native-app-boilerplate.git
foundation=${PS5_NATIVE_FOUNDATION:-$root/.deps/ps5-native-app-boilerplate}
xash=$root/third_party/xash3d-fwgs
hlsdk=$root/third_party/hlsdk-portable
boot_map=${XASH_BOOT_MAP:-c1a0}
gate_seconds=${XASH_GATE_SECONDS:-90}
jobs=${XASH_JOBS:-$(nproc)}
dev_conf=${PS5LOG_DEV_CONF:-$root/dev.conf}
game_data=${XASH_GAME_DATA:-}
objcopy=${LLVM_OBJCOPY:-$(command -v llvm-objcopy-18 || command -v llvm-objcopy || true)}
# Relocatable module links use a host linker: the SDK lld emits one .rela.text
# per COMDAT group when merging, which the final link then rejects.
ld_reloc=${LD_RELOCATABLE:-$(command -v ld.lld-18 || command -v ld.bfd || command -v ld || true)}

[[ $boot_map =~ ^[A-Za-z0-9_]+$ ]] || { echo "XASH_BOOT_MAP must be a map name" >&2; exit 2; }
[[ $gate_seconds =~ ^[0-9]+$ ]] || { echo "XASH_GATE_SECONDS must be an integer" >&2; exit 2; }
[[ -n $objcopy && -x $objcopy ]] || { echo "llvm-objcopy is required" >&2; exit 2; }
[[ -n $ld_reloc && -x $ld_reloc ]] || { echo "a host ld for relocatable links is required" >&2; exit 2; }
[[ -f $xash/engine/common/host.c ]] || {
    echo "third_party/xash3d-fwgs is not checked out; run git submodule update --init" >&2
    exit 2
}
[[ -f $hlsdk/dlls/h_export.cpp ]] || {
    echo "third_party/hlsdk-portable is not checked out; run git submodule update --init" >&2
    exit 2
}
if [[ ! -f $xash/3rdparty/library_suffix/include/build.h ||
      ! -f $xash/3rdparty/bzip2/bzip2/bzlib.c ]]; then
    git -C "$xash" submodule update --init 3rdparty/library_suffix 3rdparty/bzip2/bzip2
fi

if [[ ! -d $foundation/.git ]]; then
    mkdir -p -- "$(dirname -- "$foundation")"
    git clone --filter=blob:none "$url" "$foundation"
fi
actual=$(git -C "$foundation" rev-parse HEAD)
if [[ $actual != "$pin" ]]; then
    git -C "$foundation" fetch origin "$pin"
    git -C "$foundation" checkout --detach "$pin"
fi
[[ $(git -C "$foundation" rev-parse HEAD) == "$pin" ]] || {
    echo "native foundation pin verification failed" >&2; exit 2;
}
make -C "$foundation" deps libc >/dev/null

sdk="$foundation/.deps/native/ps5-payload-sdk"
native="$foundation/tooling/native"
tool="$foundation/build/host/ps5-native-tool"
if [[ ! -x $tool ]]; then
    zlib_root="$foundation/.deps/native/zlib/root"
    zlib_archive=$(find "$zlib_root" -type f -name libz.a -print -quit)
    cxx=$(command -v clang++-18 || command -v clang++ || true)
    [[ -n $cxx && -n $zlib_archive ]] || {
        echo "native foundation host-tool dependencies are unavailable" >&2
        exit 2
    }
    mkdir -p "$foundation/build/host"
    "$cxx" -std=c++20 -O2 -Wall -Wextra -Werror \
        -I "$zlib_root/usr/include" \
        "$native/native_app_builder.cpp" "$native/self_container.cpp" \
        "$native/elf_object.cpp" "$native/sce_module_writer.cpp" \
        "$zlib_archive" -o "$tool"
fi
[[ -x $tool && -d $sdk && -f $foundation/runtime/libc.prx ]] || {
    echo "native foundation did not produce its SDK, tool and runtime" >&2
    exit 2
}

title_id=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["titleId"])' \
    "$root/sce_sys/param.json")
build="$root/build/engine-boot"
dist="$root/dist/engine-boot/$title_id"
gen="$build/generated"
rm -rf -- "$build" "$dist"
mkdir -p "$build/obj" "$gen/bzip2" "$dist/sce_sys" "$dist/sce_module"

engine_commit=$(git -C "$xash" rev-parse --short=7 HEAD)
engine_date=$(git -C "$xash" log -1 --format=%cs HEAD)
hlsdk_commit=$(git -C "$hlsdk" rev-parse --short=7 HEAD)
cat > "$gen/vcs_info_server.c" <<VCS
/* generated by xash/build_engine.sh; hlsdk's waf normally emits this */
const char *g_VCSInfo_Commit = "$hlsdk_commit";
const char *g_VCSInfo_Branch = "ps5";
VCS
cat > "$gen/ps5_xash_build.h" <<HEADER
/* generated by xash/build_engine.sh; do not edit */
#define PS5_XASH_ENGINE_COMMIT "$engine_commit"
#define PS5_XASH_HLSDK_COMMIT "$hlsdk_commit"
#define PS5_XASH_BOOT_MAP "$boot_map"
#define PS5_XASH_GATE_SECONDS $gate_seconds
#define PS5_XASH_TITLE_ID "$title_id"
HEADER
sed 's/@BZ_VERSION@/1.1.0-fwgs/' "$xash/3rdparty/bzip2/bzip2/bz_version.h.in" \
    > "$gen/bzip2/bz_version.h"
python3 "$root/xash/tools/generate_static_library_tables.py" "$gen" \
    filesystem_stdio="$root/xash/exports/filesystem_stdio.txt" \
    server="$root/xash/exports/server.txt"

cc=(env PS5_PAYLOAD_SDK="$sdk" sh "$foundation/tooling/prospero-clang18")
lld="$sdk/bin/prospero-lld"

engine_defines=(
    -DXASH_STATIC_LIBS=1 -DXASH_DEDICATED=1 -DXASH_NO_LIBDL=1
    -DXASH_CRASHHANDLER=0 -DXASH_LOW_MEMORY=0 -DENGINE_DLL=1
    -DXASH_PS5=1 -DXASH_TIMER=TIMER_POSIX -DXASH_MESSAGEBOX=MSGBOX_STDERR
    "-DXASH_GAMEDIR=\"valve\"" "-DXASH_BUILD_COMMIT=\"$engine_commit\""
    "-DXASH_BUILD_BRANCH=\"ps5\"" "-DXASH_BUILD_COMMIT_DATE=\"$engine_date\""
    "-DSTDINT_H=<stdint.h>" "-DALLOCA_H=<stdlib.h>"
    # libc functions the SDK stubs export (checked with llvm-nm on target/lib)
    -DHAVE_STRCASECMP=1 -DHAVE_STRCASESTR=1 -DHAVE_STRNLEN=1 -DHAVE_STRLCPY=1 -DHAVE_STRLCAT=1
)
engine_includes=(
    -I"$gen" -I"$root/xash/platform_ps5" -I"$root/native/ps5log"
    -I"$xash/3rdparty/library_suffix/include"
    -I"$xash/engine" -I"$xash/engine/common" -I"$xash/engine/common/imagelib"
    -I"$xash/engine/common/soundlib" -I"$xash/engine/server"
    -I"$xash/engine/platform" -I"$xash/engine/client" -I"$xash/common" -I"$xash/public"
    -I"$xash/pm_shared" -I"$xash/filesystem" -I"$xash/3rdparty"
    -I"$xash/3rdparty/bzip2/bzip2" -I"$gen/bzip2"
)
cflags=(-O2 -w -fno-strict-aliasing -ffunction-sections -fdata-sections)
# Modules go through ld -r; lld rejects relocatable output whose merged
# sections carry several relocation sections, so they keep whole sections.
module_cflags=(-O2 -w -fno-strict-aliasing)

# Compile a list of sources (stdin, one per line, absolute) into $1 with
# the flags in the remaining arguments; prints the object paths.
compile_set() {
    local list=$1; shift
    local outdir=$1; shift
    local std=$1; shift
    mkdir -p "$outdir"
    local src
    local -a sources=()
    while IFS= read -r src; do sources+=("$src"); done
    : > "$list"
    printf '%s\0' "${sources[@]}" | xargs -0 -P "$jobs" -I{} sh -c '
        src=$1; shift; outdir=$1; shift
        obj="$outdir/$(printf "%s" "$src" | sed "s|[/ ]|_|g").o"
        "$@" -c "$src" -o "$obj" || { echo "FAILED $src" >&2; exit 1; }
    ' _ {} "$outdir" "${cc[@]}" "$std" "$@" || { echo "compilation failed" >&2; exit 1; }
    for src in "${sources[@]}"; do
        printf '%s\n' "$outdir/$(printf "%s" "$src" | sed "s|[/ ]|_|g").o" >> "$list"
    done
}

echo "== engine (dedicated, static libs)"
engine_sources=$(
    find "$xash/engine/common" "$xash/engine/server" -maxdepth 1 -name '*.c'
    find "$xash/engine/common/imagelib" "$xash/engine/common/soundlib" \
         "$xash/engine/common/http" -name '*.c'
    find "$xash/public" -maxdepth 1 -name '*.c'
    find "$xash/engine/platform/posix" -name '*.c' \
        ! -name 'sys_posix.c' ! -name 'crash_*.c' ! -name 'lib_posix.c'
    echo "$xash/engine/platform/misc/lib_static.c"
    echo "$xash/3rdparty/library_suffix/src/library_suffix.c"
    echo "$root/xash/platform_ps5/sys_ps5.c"
    echo "$root/xash/platform_ps5/boot_ps5.c"
    for f in blocksort huffman crctable randtable compress decompress bzlib; do
        echo "$xash/3rdparty/bzip2/bzip2/$f.c"
    done
    echo "$root/native/ps5log/ps5log_ps5_net.c"
)
printf '%s\n' "$engine_sources" | sort -u |
    compile_set "$build/engine.objects" "$build/obj/engine" -std=gnu11 "${cflags[@]}" \
        "${engine_defines[@]}" "${engine_includes[@]}"
mapfile -t engine_objects < "$build/engine.objects"
"${cc[@]}" -std=c11 "${cflags[@]}" -I"$root/native/ps5log" \
    -include "$root/native/ps5log/ps5log_ps5_net.h" \
    -c "$root/native/ps5log/ps5log.c" -o "$build/obj/ps5log.o"
engine_objects+=("$build/obj/ps5log.o")

# Relocatable module: link its objects into one object and keep only the
# generated export table global, exactly like xshlib does with ld -r/objcopy.
build_module() {
    local name=$1; shift
    local -a objs=("$@")
    "$ld_reloc" -r -o "$build/$name.unstripped.o" "${objs[@]}"
    "$objcopy" -G "lib_${name}_exports" "$build/$name.unstripped.o" "$build/$name.o"
}

echo "== filesystem_stdio module"
fs_sources=$(find "$xash/filesystem" -maxdepth 1 -name '*.c'; echo "$gen/link_helper_filesystem_stdio.c")
printf '%s\n' "$fs_sources" | sort -u |
    compile_set "$build/filesystem.objects" "$build/obj/filesystem" -std=gnu11 "${module_cflags[@]}" \
        "${engine_defines[@]}" "${engine_includes[@]}"
mapfile -t fs_objects < "$build/filesystem.objects"
"${cc[@]}" -std=gnu++11 "${module_cflags[@]}" -fno-exceptions -fno-rtti \
    "${engine_defines[@]}" "${engine_includes[@]}" \
    -c "$xash/filesystem/VFileSystem009.cpp" -o "$build/obj/filesystem/VFileSystem009.o"
fs_objects+=("$build/obj/filesystem/VFileSystem009.o")
build_module filesystem_stdio "${fs_objects[@]}"

echo "== server module (hlsdk-portable)"
server_defines=(-DCLIENT_WEAPONS -DNO_VOICEGAMEMGR -Dstricmp=strcasecmp
    -Dstrnicmp=strncasecmp -D_snprintf=snprintf -D_vsnprintf=vsnprintf)
server_includes=(-I"$hlsdk/dlls" -I"$hlsdk/common" -I"$hlsdk/engine"
    -I"$hlsdk/pm_shared" -I"$hlsdk/game_shared" -I"$hlsdk/public")
server_cxx=$(find "$hlsdk/dlls" -name '*.cpp' \
    ! -name 'mpstubb.cpp' ! -name 'stats.cpp' ! -name 'Wxdebug.cpp')
server_c=$(find "$hlsdk/pm_shared" -name '*.c'; echo "$hlsdk/public/safe_snprintf.c"
    echo "$hlsdk/external/openbsd/strlcpy.c"; echo "$hlsdk/external/openbsd/strlcat.c"
    echo "$gen/link_helper_server.c"; echo "$gen/vcs_info_server.c")
printf '%s\n' "$server_cxx" | sort -u |
    compile_set "$build/server-cxx.objects" "$build/obj/server" -std=gnu++11 "${module_cflags[@]}" \
        -fno-exceptions -fno-rtti "${server_defines[@]}" "${server_includes[@]}"
printf '%s\n' "$server_c" | sort -u |
    compile_set "$build/server-c.objects" "$build/obj/server" -std=gnu11 "${module_cflags[@]}" \
        "${server_defines[@]}" "${server_includes[@]}"
mapfile -t server_objects < "$build/server-cxx.objects"
mapfile -t server_c_objects < "$build/server-c.objects"
build_module server "${server_objects[@]}" "${server_c_objects[@]}"

echo "== link"
"${cc[@]}" -std=c++20 -O2 -fno-exceptions -fno-rtti \
    -ffunction-sections -fdata-sections -c "$native/app_crt.cpp" \
    -o "$build/obj/app_crt.o"
"$lld" -T "$native/ps5-pie.ld" --eh-frame-hdr \
    --version-script "$native/app-symbols.map" -e _start \
    -o "$build/llvm-pie.elf" "$build/obj/app_crt.o" "${engine_objects[@]}" \
    "$build/filesystem_stdio.o" "$build/server.o" \
    --as-needed "$sdk"/target/lib/*.so
"$tool" link --in "$build/llvm-pie.elf" --out "$build/eboot.elf" \
    --stub-dir "$sdk/target/lib" --module-sdk 0x02000009 \
    --companion-sdk 0x08050001 --file-name eboot.elf
"$tool" self --sign --in "$build/eboot.elf" --out "$dist/eboot.bin" \
    --magic 0x1D3D154F
cp "$root/sce_sys/param.json" "$root/sce_sys/icon0.png" "$dist/sce_sys/"
cp "$foundation/runtime/libc.prx" "$dist/sce_module/libc.prx"
if [[ -f $dev_conf ]]; then
    cp "$dev_conf" "$dist/dev.conf"
fi
if [[ -n $game_data ]]; then
    [[ -d $game_data/valve ]] || {
        echo "XASH_GAME_DATA must contain a valve/ directory" >&2; exit 2;
    }
    mkdir -p "$dist/xash3d"
    cp -R "$game_data/valve" "$dist/xash3d/valve"
    echo "staged game data: $(find "$dist/xash3d" -type f | wc -l) files (private, not published)"
fi
(cd "$root" && sha256sum "${build#"$root/"}/eboot.elf" "${dist#"$root/"}/eboot.bin") > "$build/SHA256SUMS"
"$tool" self --inspect --file "$dist/eboot.bin"
cat "$build/SHA256SUMS"
echo "engine=$engine_commit hlsdk=$hlsdk_commit map=$boot_map gate_seconds=$gate_seconds"
