#!/usr/bin/env python3
"""Generate a PRXDESC1 source and export map from a bounded symbol list."""

from __future__ import annotations

import argparse
import pathlib
import sys

sys.dont_write_bytecode = True

from generate_static_library_tables import NAME_RE, parse_exports


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--module", required=True)
    parser.add_argument("--exports", required=True, type=pathlib.Path)
    parser.add_argument("--source", required=True, type=pathlib.Path)
    parser.add_argument("--version-script", required=True, type=pathlib.Path)
    parser.add_argument("--extra", action="append", default=[])
    args = parser.parse_args()
    if not NAME_RE.fullmatch(args.module):
        parser.error("--module must be a C identifier")
    exports = parse_exports(args.exports.read_text(encoding="utf-8"))
    if any(not NAME_RE.fullmatch(name) for name in args.extra):
        parser.error("--extra values must be C identifiers")
    if len(args.extra) != len(set(args.extra)):
        parser.error("--extra values must be unique")
    lifecycle = args.extra + [
        f"PS5_{args.module.title()}PrxState",
        f"PS5_{args.module.title()}PrxExportCount",
        "module_start",
        "module_stop",
    ]
    if set(exports) & set(lifecycle):
        parser.error("engine exports overlap the generated lifecycle exports")
    descriptor = f"{args.module}_prx_exports"
    externs = "\n".join(f"extern void {name}(void);" for name in exports + args.extra)
    rows = "\n\t".join(f"PS5_PRX_EXPORT( {name} )," for name in exports)
    rows += "\n\t" + ",\n\t".join(f"PS5_PRX_EXPORT( {name} )" for name in lifecycle)
    title = args.module.title()
    source = f"""/* generated by generate_prx_descriptor.py; do not edit */
#include \"prx_loader_ps5.h\"

{externs}

static int ps5_{args.module}_prx_started;
typedef void (*ps5_prx_initializer_t)( void );
extern ps5_prx_initializer_t __init_array_start[] __attribute__((weak));
extern ps5_prx_initializer_t __init_array_end[] __attribute__((weak));
extern ps5_prx_initializer_t __fini_array_start[] __attribute__((weak));
extern ps5_prx_initializer_t __fini_array_end[] __attribute__((weak));

static void ps5_prx_run_initializers( void )
{{
    ps5_prx_initializer_t *entry;
    if( !__init_array_start || !__init_array_end ) return;
    for( entry = __init_array_start; entry != __init_array_end; ++entry )
        if( *entry ) ( *entry )( );
}}

static void ps5_prx_run_finalizers( void )
{{
    ps5_prx_initializer_t *entry;
    if( !__fini_array_start || !__fini_array_end ) return;
    entry = __fini_array_end;
    while( entry != __fini_array_start )
    {{
        --entry;
        if( *entry ) ( *entry )( );
    }}
}}

/* FreeBSD's assert destination is not part of libSceLibcInternal. Assertions
 * inside an application-owned module are unrecoverable and must not become a
 * dangling firmware import. */
__attribute__((noreturn))
void __assert( const char *function, const char *file, int line,
    const char *expression )
{{
    (void)function; (void)file; (void)line; (void)expression;
    __builtin_trap( );
}}

int PS5_{title}PrxState( void ) {{ return ps5_{args.module}_prx_started; }}
int PS5_{title}PrxExportCount( void ) {{ return {len(exports)}; }}
int module_start( size_t argc, const void *argv )
{{
    (void)argc; (void)argv;
    if( ps5_{args.module}_prx_started ) return 0;
    ps5_prx_run_initializers( );
    ps5_{args.module}_prx_started = 1;
    return 0;
}}
int module_stop( size_t argc, const void *argv )
{{
    (void)argc; (void)argv;
    if( !ps5_{args.module}_prx_started ) return 0;
    ps5_prx_run_finalizers( );
    ps5_{args.module}_prx_started = 0;
    return 0;
}}

PS5_PRX_DEFINE_DESCRIPTOR( {descriptor},
\t{rows} );
"""
    globals_ = exports + lifecycle + [descriptor]
    version_script = "{\n\tglobal:\n" + "".join(
        f"\t\t{name};\n" for name in globals_) + "\tlocal:\n\t\t*;\n};\n"
    args.source.parent.mkdir(parents=True, exist_ok=True)
    args.version_script.parent.mkdir(parents=True, exist_ok=True)
    args.source.write_text(source, encoding="utf-8")
    args.version_script.write_text(version_script, encoding="utf-8")
    print(f"{args.module} PRX descriptor: {len(exports)} engine exports, "
          f"{len(lifecycle)} support exports")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
