#!/usr/bin/env python3
"""Generate the static library tables Xash3D expects with XASH_STATIC_LIBS.

Xash3D's waf build (scripts/waifulib/xshlib.py) links every engine module as a
relocatable object whose only global symbol is ``lib_<name>_exports`` and
resolves ``COM_LoadLibrary``/``COM_GetProcAddress`` through generated tables.
This script reproduces those two generated artefacts without waf:

* ``generated_library_tables.h`` included by ``engine/platform/misc/lib_static.c``
* ``link_helper_<name>.c`` for each module, compiled into that module

Usage: generate_static_library_tables.py OUT_DIR NAME=EXPORTS_FILE [NAME=EXPORTS_FILE...]
"""
from __future__ import annotations

import pathlib
import re
import sys

NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def parse_exports(text: str) -> list[str]:
    exports = []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if not NAME_RE.match(line):
            raise ValueError(f"invalid export symbol: {raw!r}")
        if line in exports:
            raise ValueError(f"duplicate export symbol: {line}")
        exports.append(line)
    if not exports:
        raise ValueError("export list is empty")
    return exports


def render_tables_header(names: list[str]) -> str:
    externs = "\n".join(f"extern table_t lib_{n}_exports[];" for n in names)
    rows = "\n".join(f'{{ "{n}", &lib_{n}_exports }},' for n in names)
    return (
        "/* generated by generate_static_library_tables.py; do not edit */\n"
        f"{externs}\n"
        "struct {const char *name;void *func;} libs[] = {\n"
        f"{rows}\n"
        "{0,0}\n"
        "};\n"
    )


def render_link_helper(name: str, exports: list[str]) -> str:
    externs = "\n".join(f"extern void {e}(void);" for e in exports)
    rows = "\n".join(f'{{ "{e}", &{e} }},' for e in exports)
    return (
        "/* generated by generate_static_library_tables.py; do not edit */\n"
        f"{externs}\n"
        f"struct {{const char *name;void *func;}} lib_{name}_exports[] = {{\n"
        f"{rows}\n"
        "{0,0}\n"
        "};\n"
    )


def parse_spec(spec: str) -> tuple[str, pathlib.Path]:
    name, sep, path = spec.partition("=")
    if not sep or not NAME_RE.match(name) or not path:
        raise ValueError(f"expected NAME=EXPORTS_FILE, got {spec!r}")
    return name, pathlib.Path(path)


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        sys.stderr.write(__doc__)
        return 2
    out_dir = pathlib.Path(argv[1])
    out_dir.mkdir(parents=True, exist_ok=True)
    names: list[str] = []
    for spec in argv[2:]:
        name, exports_path = parse_spec(spec)
        if name in names:
            raise ValueError(f"duplicate library name: {name}")
        exports = parse_exports(exports_path.read_text(encoding="utf-8"))
        (out_dir / f"link_helper_{name}.c").write_text(
            render_link_helper(name, exports), encoding="utf-8")
        names.append(name)
    (out_dir / "generated_library_tables.h").write_text(
        render_tables_header(names), encoding="utf-8")
    print(f"static library tables: {', '.join(names)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
